model_type: fluxvla_pi05
model_path: ???
precision: fp32
load_to_device: true
is_lora: false
lora_rank: 32
num_action_chunks: 10
action_dim: 7
num_steps: 10
use_proprio: true
add_value_head: true
joint_logprob: false
fluxvla:
  config_path: ${oc.env:FLUXVLA_ROOT}/configs/pi05/pi05_paligemma_libero_10_full_finetune.py
  tokenizer_path: null
  norm_stats_path: null
  compute_dtype: bf16
  train_expert_only: true
  noise_method: flow_sde
  noise_level: 0.5
