defaults:
  - _robotwin_8gpu_base
  - _self_

hydra:
  searchpath:
    - file://${oc.env:RLINF_CONFIG_DIR}

experiment:
  split: test

rollout:
  model: ${actor.model}

runner:
  only_eval: true
  logger:
    experiment_name: adjust_bottle_8gpu_sft_test
    logger_backends: [tensorboard]

env:
  eval:
    total_num_envs: 10
    rollout_epoch: 15
    video_cfg:
      save_video: true
      fps: 1
      video_base_dir: ${runner.logger.log_path}/${runner.logger.experiment_name}/videos
