# @package _global_

defaults:
  - /benchmarks/libero/smolvla/base
  - _self_

hydra:
  searchpath:
    - file://${oc.env:RLINF_CONFIG_DIR}

runner:
  only_eval: true
  logger:
    experiment_name: libero_10_eval_fluxvla_smolvla
